import "../globals.css";
import { verifyAuth } from "@/lib/auth";
import Header from "@/components/Header";
import { redirect } from "next/navigation";
import connectDB from "@/lib/db";

export const metadata = {
  title: "Lucia Data",
  description: "Generated by Next.js",
};

const initialDatabase = async () => {
  try {
    await connectDB();
  } catch (err) {
    console.log(err);
  }
};

initialDatabase();

export default async function RootLayout({ children }) {
  const { user } = await verifyAuth();

  if (!user) {
    redirect("/login");
  }

  return (
    <html lang="en" data-theme="corporate">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
